name: Build OS image

on:
  push:
    branches: [ master ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: build
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils
            sudo --preserve-env=SSH_AUTH_SOCK ./build.sh

      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: OS image
          path: deploy/*.zip
