name: Build OS image for testing

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: build
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils
            sudo --preserve-env=SSH_AUTH_SOCK ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: deploy/*.zip
