name: Build OS image for testing

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN_MIND }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build-button:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: dependencies
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils

      - name: Button
        run: sudo --preserve-env=SSH_AUTH_SOCK,GH_TOKEN ./build.sh Button

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tester-image-button
          path: deploy/*
          retention-days: 30

  build-distance:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: dependencies
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils

      - name: Distance
        run: sudo --preserve-env=SSH_AUTH_SOCK,GH_TOKEN ./build.sh Distance

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tester-image-distance
          path: deploy/*
          retention-days: 30

  build-color:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: dependencies
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils

      - name: Color
        run: sudo --preserve-env=SSH_AUTH_SOCK,GH_TOKEN ./build.sh Color

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tester-image-color
          path: deploy/*
          retention-days: 30

  build-motor:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: dependencies
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils

      - name: Motor
        run: sudo --preserve-env=SSH_AUTH_SOCK,GH_TOKEN ./build.sh Motor

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tester-image-motor
          path: deploy/*
          retention-days: 30
