name: Build OS image

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: build
        run: |
            sudo apt-get update
            sudo apt-get install quilt qemu-user-static debootstrap libarchive-tools qemu-utils
            sudo --preserve-env=SSH_AUTH_SOCK ./build.sh
      
      - name: Upload image to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*.zip
          file_glob: true
          asset_name: Pi-OS image
          tag: ${{ github.ref }}
          promote: true # create a pre-release to trigger workflow, then promote to release when done
